- hosts: minikube
  become: true
  tasks:
    - name: Create Kubernetes Deployment
      command: kubectl apply -f /home/ubuntu/Deployment.yml --validate=false
    - name: Create Kubernetes Service
      command: kubectl apply -f /home/ubuntu/service.yml --validate=false
    - name: Verify Deployment rollout status
      command: kubectl rollout status deployment/webapp
    - name: Get Service details
      command: kubectl get service webapp
